name: Run Azure Login with OIDC, Updating Infrastructure
on:
  push:
    branches:
      - main
    paths:
      - 'yaml_files/**'
  workflow_dispatch:
permissions:
      id-token: write
      contents: read
      packages: write
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name hedgehogsacr 

      - name: Link runner to cluster
        run: az aks get-credentials --resource-group hedgehogs-chapter-4 --name hedgehogs-cluster
        
      - name: Query ACR for latest UI image
        run: echo "TAG=$(az acr repository show-tags -n hedgehogsacr --repository ui --top 1 --orderby time_desc | tr -d '["] \n')" >> $GITHUB_ENV

      - name: Redeploy UI
        run: envsubst < ./deployments/ui-deployment.yaml | kubectl apply -f -

      - name: Query ACR for latest API image
        run: echo "TAG=$(az acr repository show-tags -n hedgehogsacr --repository api --top 1 --orderby time_desc | tr -d '["] \n')" >> $GITHUB_ENV

      - name: Redeploy API
        run: envsubst < ./deployments/api-deployment.yaml | kubectl apply -f -


      - name: Applying Infrastructure Changes
        run: |
          kubectl apply -f yaml_files

